/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#920028",
        "on-primary-fixed": "#40000c",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#5c3f40",
        "surface": "#f7f9fb",
        "on-tertiary-container": "#fcfaff",
        "primary-container": "#e11d48",
        "inverse-primary": "#ffb3b6",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-dim": "#d8dadc",
        "on-secondary-container": "#fefcff",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#131b2e",
        "secondary": "#0051d5",
        "inverse-surface": "#2d3133",
        "tertiary": "#535b71",
        "on-primary-container": "#fffaf9",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#316bf3",
        "tertiary-fixed-dim": "#bec6e0",
        "primary": "#b80035",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#6c738a",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#ffb3b6",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#e5bdbe",
        "outline": "#906f70",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "background": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#dbe1ff",
        "on-secondary-fixed": "#00174b",
        "surface-container": "#eceef0",
        "primary-fixed": "#ffdada",
        "secondary-fixed-dim": "#b4c5ff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-tint": "#be0037",
        "tertiary-fixed": "#dae2fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "sidebar-width": "280px",
        "gutter": "24px",
        "stack-sm": "8px",
        "margin-desktop": "48px",
        "container-max": "1440px",
        "stack-md": "16px"
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "metadata": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "metadata": ["13px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "display-hero": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
